## 问答题
### 1. 什么是错误处理？为什么要错误处理？  
>当 JavaScript 引擎执行 JavaScript 代码时，会发生各种错误,在不处理的
情况下,程序会终止执行.  
通过js的机制,对抛出的错误进行操作,是错误处理.  

### 2. 常见的错误有哪些？  
* EvalError(eval错误)
* **RangeError(范围错误)**
* **ReferenceError(引用错误)**
* **SyntaxError(语法错误)**
* TypeError(类型错误)
* URIError(URI错误)

### 3. 能用 `if` 语句替代错误处理吗？如果能，请给出实例代码，如果不能，请说明原因（开放题）  
>不能.抛出错误后,不进行错误处理程序会停止.if无法完成错误处理.

### 4. 如何抛出一个错误？  
```js
// throw主动抛出
throw new Error("a error")

// 系统抛出,a未声明
console.log(a);
```

### 5. 以下代码可以捕获异常吗？为什么？
```js
function a(){
 throw new Error("An error")
}
function b(){
 a();
}
try{
 b()
}catch(err){
 console.log(err)
}
```  
>能.异常会向上层抛出,如果上层函数不进行错误处理,会继续向上抛出.

### 6. `finally` 子句有什么用？  
>try从句定义了需要处理的异常所在的代码块。catch从句跟随在try从句之后，当try块内某处发生了异常时，调用catch内的代码逻辑。catch从句后跟随finally块，后者中放置清理代码，不管try块中是否产生异常，finally块内的逻辑总是会执行

### 7. JavaScript 中 `throw`可以抛出非 `Error` 类型的异常吗？请动手试试  
>可以.都可以抛出,试了.

### 8. `try catch` 语句可以嵌套吗？ 如何嵌套？  
>可以嵌套.
```js
try{
}catch(err_1){
	try{
	}catch(err_2){
	}finally{
	}
}finally{
	try{
	}catch(err_3){
	}finally{
  }
}
```

## 代码题
### 1. 请构造一段会产生异常的代码（注意：不是一定会产生，是有一定概率产生异常），然后使用异常处理机制处理它.  
```js
try{
  a.toString();
}catch(e){
  console.log(e);
}finally{
  console.log("finally语句");
}
```

### 2. 以下代码能不能正常捕获异常，如果不能请分析原因并修改代码使其可以正常捕获异常.
```js
function asyncTask(){
 setTimeout(function(){
   throw new Error("An error")
 },1000)
}
try{
 asyncTask()
} catch(err){
 console.log(err)
}
```
>不能.

>reason:Functions scheduled to run with setTimeout are executed in the main loop, outside the body of code that originated them.  
To handle errors, put the try-catch inside the setTimeout handler.  
setTimeout()定时调用的函数不在调用的函数体里,而在main loop中执行.  
修改方式如下.  

```js
function asyncTask(){
 setTimeout(function(){
   try{
     throw new Error("An error");
   }catch(err){
     console.log(err)
   }finally{
   }
   
 },1000);
}

try{
 asyncTask()
} catch(err){
 console.log(err);
}
```
